BEGIN {
		print "// Automatically-generated typecasting operators for SDPGTK events"
		print "//"
		print "// This file was generated with 'awk -f sdpgtkeventscasting.awk sdpgtkevents.data > include/sdpgtkeventscasting.h'"
		print "// Do not edit this file by hand!  Alter sdpgtkeventscasting.awk or sdpgtkevents.data!"
		print ""
		print ""

		FS = " "
}




# Create operator ...
{
	class = $1
	signal = $2

	print "  class " class "; inline operator " class "*() { g_assert(m_EventSignal == \"" signal "\"); return (" class "*)this; }"
}

